version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: romashka-rabbitmq
    ports:
      - "5672:5672"  # Порт для AMQP
      - "15672:15672"  # Порт для веб-интерфейса
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres-brt:
    image: postgres:15
    container_name: romashka-brt-postgres
    environment:
      POSTGRES_DB: brt_db
      POSTGRES_USER: brt_user
      POSTGRES_PASSWORD: brt_pass
    ports:
      - "5432:5432"
    volumes:
      - brt_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-hrs:
    image: postgres:15
    container_name: romashka-hrs-postgres
    environment:
      POSTGRES_DB: hrs_db
      POSTGRES_USER: hrs_user
      POSTGRES_PASSWORD: hrs_pass
    ports:
      - "5433:5432"
    volumes:
      - hrs_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  cdr:
    build:
      context: ./cdr
      dockerfile: Dockerfile
    container_name: cdr
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker,simulation
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      TIME_COEFFICIENT: "175200.0" # "87600.0" # в реальной системе: TIME_COEFFICIENT: "1.0"
      TIME_START: "2025-01-01T00:00:00"
      TIME_END: "2025-12-31T23:59:59"

  brt:
    build:
      context: ./brt
      dockerfile: Dockerfile
    container_name: brt
    ports:
      - "8081:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-brt:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-brt:5432/brt_db
      SPRING_DATASOURCE_USERNAME: brt_user
      SPRING_DATASOURCE_PASSWORD: brt_pass
      TIME_COEFFICIENT: "87600.0" # "175200.0" # в реальной системе: TIME_COEFFICIENT: "1.0"
      TIME_START: "2025-01-01T00:00:00"
      TIME_END: "2025-12-31T23:59:59"

  hrs:
    build:
      context: ./hrs
      dockerfile: Dockerfile
    container_name: hrs
    ports:
      - "8082:8082"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-hrs:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-hrs:5432/hrs_db
      SPRING_DATASOURCE_USERNAME: hrs_user
      SPRING_DATASOURCE_PASSWORD: hrs_pass
      TIME_COEFFICIENT: "87600.0" # "175200.0" # в реальной системе: TIME_COEFFICIENT: "1.0"
      TIME_START: "2025-01-01T00:00:00"
      TIME_END: "2025-12-31T23:59:59"

volumes:
  brt_pgdata:
  hrs_pgdata:
