# ---------------------------------------------------------
# Общие настройки сервиса
# ---------------------------------------------------------

time:
  start: ${TIME_START:2025-01-01T00:00:00}
  end: ${TIME_END:2025-12-31T23:59:59}
  coefficient: ${TIME_COEFFICIENT:175200.0}  # 87600.0

# ---------------------------------------------------------
# Общие настройки RabbitMQ (всегда активны)
# ---------------------------------------------------------
rabbitmq:
  hrs:
    exchange:
      name: brt.exchange
    queue:
      name: brt.queue
    routing:
      key: brt.routingkey
  cdr:
    exchange:
      name: cdr.exchange
    queue:
      name: cdr.queue
    routing:
      key: cdr.routingkey

---
# ---------------------------------------------------------
# Default‑профиль (локальная разработка)
# ---------------------------------------------------------
spring:
  config:
    activate:
      on-profile: default

  application:
    name: romashka-telecom

  datasource:
    url: jdbc:h2:mem:roaming_brt_db;
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    connection-timeout: 5000
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000ms
          max-interval: 10000ms
          max-attempts: 3
        missing-queues-fatal: false
    template:
      message-converter: messageConverter
      retry:
        enabled: true
        initial-interval: 2000ms
        max-interval: 10000ms
        max-attempts: 3

---
# ---------------------------------------------------------
# Docker‑профиль (PostgreSQL + Liquibase)
# ---------------------------------------------------------
spring:
  config:
    activate:
      on-profile: docker

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10000
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3000ms
          max-interval: 10000ms
          max-attempts: 3
    template:
      retry:
        enabled: true
        initial-interval: 3000
        max-interval: 10000
        max-attempts: 3
      missing-queues-fatal: false

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # пытаюсь исправить блокировку
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:db/clear_liquibase_lock.sql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true

  liquibase:
    enabled: false
#    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.yaml

  server:
    port: 8081

# Настройки приложения
app:
  export:
    batch-size: 10
    retry-attempts: 3
    retry-delay: 1000

# Логирование
logging:
  level:
    org.springframework.amqp: DEBUG
    com.romashka.romashka_telecom: INFO
    root: WARN
    liquibase: DEBUG
